### ISSUE TITLE
Webservice Page Not Work

### ISSUE THREAD

**Issue by AnggitHerdianto** [MattLoyeD/Prestashop-Nginx#3]
Hi, 

I'm use this config and work very well expect webservice page, this page return 500 error.

http://localhost:8002/admin_page/index.php?controller=AdminWebservice

**Comment by AnggitHerdianto** [comment]
Sorry for my bad, it's not nginx config error but php error.

**Comment by diditnurcahya** [comment]
Salam, mas kalau bagian nilai UN dibuat 2 digit nomor bagaimana ya? seperti model nilai UN jaman sekarang
![nilai un](https://user-images.githubusercontent.com/46638252/60066810-6a5ab800-9732-11e9-8d1d-c35e588b9fa8.jpg)

**Comment by diditnurcahya** [comment]
mohon maaf, saya mau tanya
ketika delete siswa, muncul pesan berikut kenapa ya mas?
![64983526_2416396828636307_4521185632956973056_n](https://user-images.githubusercontent.com/46638252/60067121-8e6ac900-9733-11e9-838b-d6aa44b9668c.png)
